### ISSUE TITLE
labs.data.gov/dashboard/offices has PHP error

### ISSUE THREAD

**Issue by rubixcuban** [project-open-data/project-open-data-dashboard#128]
A PHP Error was encountered

Severity: Notice

Message: Undefined index: show_totals

Filename: views/office_list.php

Line Number: 79

**Comment by rebeccawilliams** [comment]
Thanks @rubixcuban! I believe this issue has been resolved. Please re-open this issue if you encounter this behavior again,

**Comment by justgrimes** [comment]
Reopening this issue as it still appears to be occurring

![image](https://cloud.githubusercontent.com/assets/781944/12459080/e4ece2c0-bf7a-11e5-8816-b1bf065a0c00.png)

**Comment by philipashlock** [comment]
This has been resolved.
